### ISSUE TITLE
README Lacks any information on how to get the Utility working

### ISSUE THREAD

**Issue by g0lgs** [V96GLF/Minos-CSL-Utility#1]
README Lacks any information on how to get the Utility working.

Specifically there is no list of module requirements

On Ubuntu 24.04 I found I had to do:

sudo apt install python3-tk

to get tkinter

**Comment by V96GLF** [comment]
Thanks, Stewart. I have now added this to the README. My testing was mainly on Raspberry Pi, which does include tkinter!
